### ISSUE TITLE
Join Public Class (3)

### ISSUE THREAD

**Issue by jonathanmcdaniel** [mentii/mentii#14]
| Story Points | 3 |
| :-- | --- |
| **Owner** | Alex |
#### Description
As a student I would like to become a member of a publicly available class by selecting  it  from the list of available classes

#### Acceptance Criteria
- The user is a member of the class after joining
- The user cannot do this for any class that is not public

**Comment by aaronmsegal** [comment]
I had everything working, then when we uncovered the issue with sets in python 2.6 and I went and changed the code accordingly for user’s classCode set and classes’ student email set.

Joining class works fine, in that you can join without issue, and I can scan the local bd  and see the student's email in the class’s student string set and the class’s code in the student’s classCode string set
  
But when I hit the dashboard and load the user’s classes that fails in the backend

This Exception is produced:

`[2017-02-01 10:04:42,006] ERROR in app: Exception on /user/classes/ [GET]
Traceback (most recent call last):
  File "/Users/aaronmsegal/Development/mentii/mentii/Backend/env/lib/python2.7/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/aaronmsegal/Development/mentii/mentii/Backend/env/lib/python2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/aaronmsegal/Development/mentii/mentii/Backend/env/lib/python2.7/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/Users/aaronmsegal/Development/mentii/mentii/Backend/env/lib/python2.7/site-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/aaronmsegal/Development/mentii/mentii/Backend/env/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/aaronmsegal/Development/mentii/mentii/Backend/env/lib/python2.7/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/aaronmsegal/Development/mentii/mentii/Backend/env/lib/python2.7/site-packages/flask_httpauth.py", line 93, in decorated
    return f(*args, **kwargs)
  File "app.py", line 173, in class_list
    return ResponseCreation.createResponse(res, status)
  File "/Users/aaronmsegal/Development/mentii/mentii/Backend/utils/ResponseCreation.py", line 40, in createResponse
    responseString = controllerResponse.getResponseString()
  File "/Users/aaronmsegal/Development/mentii/mentii/Backend/utils/ResponseCreation.py", line 34, in getResponseString
    return json.dumps(responseDict)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 243, in dumps
    return _default_encoder.encode(obj)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: set([u'aaronmsegal@gmail.com']) is not JSON serializable`

This is in the current version of my branch

**Comment by RyanYoung25** [comment]
Looks like the error is because we're trying to add a set to a response object. The response object must be a dictionary containing dictionaries or lists because it is dumpped to a JSON string. JSON strings can only represent dictionaries and lists, not sets natively. If you're OK with it I can take a quick look at noon and see where it's all coming from.

**Comment by aaronmsegal** [comment]
Yeah go for it, I wont be able to give it serous time until friday.  Also note when this appears to be working with Jon's view taught set and was working here before changed the update statement from {classCode/email} to set([classCode/email])

**Comment by RyanYoung25** [comment]
Found the error. The problem was that for each class we were taking the data that we received directly from the db and adding it to the response that we are creating. Here is a print out of the data that we get:

{u'code': u'0b2c9f07-2016-4ac0-a168-0b3a15b6d976', u'description': u'fdsa', u'title': u'Algebra Test', u'students': set([u'ry525525@gmail.com']), u'section': u'01', u'department': u'Math'}

Note that the 'students' attribute contains a set containing my username. This can not be serialized by json and that's why you were seeing the error that we got. I added one line that rather brutishly converted the set to a list as you can see here: 

{u'code': u'0b2c9f07-2016-4ac0-a168-0b3a15b6d976', u'description': u'fdsa', u'title': u'Algebra Test', u'students': [u'ry525525@gmail.com'], u'section': u'01', u'department': u'Math'}

Whether or not we stick with the one line fix I have should be discussed. As long as the rest of the code is not adding a set directly to the response payload we should be fine. A better long term fix might be to 'clean up' the payload before jsonifying in the ResponseCreation class. 

I'm going to push a commit with my temporary fix and the two print statements around it that everyone should use to see where the bug is. I don't have time right now to fix the bug or search for other parts of the program that might be affected by this but hopefully this helps explain what's going on.
